name: CI/CD

on:
  release:
    types:
      - released

jobs:
  build:
    name: build-push

    runs-on: ubuntu-latest

    steps:
      - name: Lint tag name
        run: |
          if [[ ! "$GITHUB_REF" =~ ^refs\/tags\/v.+$ ]]; then
            echo "Invalid tag name"
            exit 1
          fi

      - uses: actions/checkout@v2

      - name: Generate image tag
        id: tag
        run: |
          echo ::set-output name=tag::ghcr.io/z1digitalstudio/storyshots-runner:${GITHUB_REF#refs/tags/v}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PUSH_PERSONAL_ACCESS_TOKEN }}

      - uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.tag.outputs.tag }}
